### ISSUE TITLE
Window doesn't appear when using WPF theme

### ISSUE THREAD

**Issue by nicoco007** [higankanshi/xZune.Vlc#110]
I just started using your VLC wrapper and, since the default WPF style is pretty terrible, I tried to add [MahApps.Metro](http://mahapps.com/) on top of it. However, when I do that, the window simply refuses to load. If I remove the VLC control **or** the styles (from App.xaml), it works properly. Any idea why?

**Edit: It does seem to work when I put the styles in the `<Window.Resources>` tag.**

**Comment by higankanshi** [comment]
Can you give me a some sample XAML code?

**Comment by nicoco007** [comment]
Of course! This is all I have currently modified (no C# code yet).

MainWindow.xaml:

	<controls:MetroWindow x:Class="MyWpfApplication1.MainWindow"
			xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
			xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
			xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
			xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
			xmlns:local="clr-namespace:MyWpfApplication1"
			xmlns:controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
			xmlns:vlc="clr-namespace:xZune.Vlc.Wpf;assembly=xZune.Vlc.Wpf"
			mc:Ignorable="d"
			Title="MainWindow" Height="450" Width="800" Loaded="Window_Loaded" WindowTransitionsEnabled="False">

			<ListView Grid.Column="0" x:Name="listView" SelectionChanged="listView_SelectionChanged">
				<ListView.View>
					<GridView>
						<GridViewColumn Width="250px">
							<GridViewColumn.Header>
								<GridViewColumnHeader>Name</GridViewColumnHeader>
							</GridViewColumn.Header>
							<GridViewColumn.CellTemplate>
								<DataTemplate>
									<TextBlock Text="{Binding Name}"/>
								</DataTemplate>
							</GridViewColumn.CellTemplate>
						</GridViewColumn>
						<GridViewColumn Width="150px">
							<GridViewColumn.Header>
								<GridViewColumnHeader>ID</GridViewColumnHeader>
							</GridViewColumn.Header>
							<GridViewColumn.CellTemplate>
								<DataTemplate>
									<TextBlock Text="{Binding Id}"/>
								</DataTemplate>
							</GridViewColumn.CellTemplate>
						</GridViewColumn>

					</GridView>
				</ListView.View>
			</ListView>
			
			<GridSplitter Grid.Column="1" Width="5" HorizontalAlignment="Stretch" />
			
			<Grid Grid.Column="2">
				<vlc:VlcPlayer x:Name="vlc" Margin="0,0,0,6" EndBehavior="Repeat" PositionChanged="vlc_PositionChanged" />
				<controls:ProgressRing x:Name="vlcLoader" Visibility="Collapsed"  Width="50" Height="50" HorizontalAlignment="Center" VerticalAlignment="Center"/>
				<controls:MetroProgressBar x:Name="progressBar" VerticalAlignment="Bottom" Height="6"/>
			</Grid>

		</Grid>
	</controls:MetroWindow>

App.xaml:

	<Application x:Class="LolScreensaverExtractor.App"
				 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
				 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
				 xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
				 xmlns:local="clr-namespace:LolScreensaverExtractor"
				 StartupUri="MainWindow.xaml">
		<Application.Resources>
			<ResourceDictionary>
				<ResourceDictionary.MergedDictionaries>
					
					<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
					<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
					<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
					<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/FlatButton.xaml" />
					
					<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
					<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
				</ResourceDictionary.MergedDictionaries>
			</ResourceDictionary>
		</Application.Resources>
	</Application>

**Comment by nicoco007** [comment]
I also sometimes randomly get a `System.Windows.Markup.XamlParseException` when starting:

	Initialization of 'xZune.Vlc.Wpf.ThreadSeparatedImage' has thrown an exception.
	   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
	   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlObjectWriter objectWriter)
	   at System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(DependencyObject container, IComponentConnector componentConnector, IStyleConnector styleConnector, List`1 affectedChildren, UncommonField`1 templatedNonFeChildrenField)
	   at System.Windows.FrameworkTemplate.LoadContent(DependencyObject container, List`1 affectedChildren)
	   at System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
	   at System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
	   at System.Windows.FrameworkElement.ApplyTemplate()
	   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   at System.Windows.UIElement.Measure(Size availableSize)
	   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
	   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   at System.Windows.UIElement.Measure(Size availableSize)
	   at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
	   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
	   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
	   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
	   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   at System.Windows.UIElement.Measure(Size availableSize)
	   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
	   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
	   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   at System.Windows.UIElement.Measure(Size availableSize)
	   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
	   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
	   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   at System.Windows.UIElement.Measure(Size availableSize)
	   at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
	   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   at System.Windows.UIElement.Measure(Size availableSize)
	   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
	   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   at System.Windows.UIElement.Measure(Size availableSize)
	   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
	   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   at System.Windows.UIElement.Measure(Size availableSize)
	   at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
	   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
	   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV)
	   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
	   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   at System.Windows.UIElement.Measure(Size availableSize)
	   at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
	   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   at System.Windows.UIElement.Measure(Size availableSize)
	   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
	   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   at System.Windows.UIElement.Measure(Size availableSize)
	   at System.Windows.Window.MeasureOverrideHelper(Size constraint)
	   at System.Windows.Window.MeasureOverride(Size availableSize)
	   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
	   at System.Windows.UIElement.Measure(Size availableSize)
	   at System.Windows.Interop.HwndSource.SetLayoutSize()
	   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
	   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
	   at System.Windows.Window.SetRootVisual()
	   at System.Windows.Window.SetRootVisualAndUpdateSTC()
	   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
	   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
	   at System.Windows.Window.CreateSourceWindowDuringShow()
	   at System.Windows.Window.SafeCreateWindowDuringShow()
	   at System.Windows.Window.ShowHelper(Object booleanBox)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at System.Windows.Application.Run(Window window)
	   at System.Windows.Application.Run()
	   at MyWpfApplication1.App.Main() in C:\...\x86\Debug\App.g.cs:line 0
	   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
	   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
	   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
	   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.ThreadHelper.ThreadStart()

with an inner exception that has the message `A task has been canceled`:

	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
	   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
	   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
	   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
	   at xZune.Vlc.Wpf.ThreadSeparatedImage.LoadThreadSeparatedControl()
	   at xZune.Vlc.Wpf.ThreadSeparatedControlHost.OnInitialized(EventArgs e)
	   at System.Windows.FrameworkElement.TryFireInitialized()
	   at System.Windows.FrameworkElement.EndInit()
	   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)

**Comment by SheppeR** [comment]
Hi, i have the same issue using 'FirstFloor.ModernUI'.
Removing Resource from my app let me show the windows without problems.
Loading external ressource break xZune.Vlc
                ```
<ResourceDictionary Source="/FirstFloor.ModernUI;component/Assets/ModernUI.xaml" />
                <ResourceDictionary Source="/FirstFloor.ModernUI;component/Assets/ModernUI.Dark.xaml" />
                <ResourceDictionary Source="/SWPlayer;component/Assets/AppAssets.xaml" />
```

**Comment by higankanshi** [comment]
I will try it later, but no idea about this issue.

**Comment by higankanshi** [comment]
I have fix it with dev branch, you can get the code of it.
The reason of case this issue is Main UI thread wait for creating ThreadSeparatedImage, and the ThreadSeparatedImage wait for Main UI thread to invoke, so it case a deadlock.

**Comment by higankanshi** [comment]
About the System.Windows.Markup.XamlParseException, this issue look like the same issue as window doesn't appear. You can have try, if it still happen, please create a issue for it.

**Comment by SheppeR** [comment]
The fix work for me
