### ISSUE TITLE
Application freezes on VlcPlayer.Dispose()

### ISSUE THREAD

**Issue by sepehr1014** [higankanshi/xZune.Vlc#18]
When trying to close the window, application freezes. Using .NET 4.5:
```C#
        public MainWindow()
        {
            InitializeComponent();

            this.Closing += Window_Closing;

            var d = new OpenFileDialog();
            if (d.ShowDialog() == true)
            {
                mediaPlayer.LoadMedia(d.FileName);
                mediaPlayer.Play();
            }
        }

        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            mediaPlayer.Dispose();
            ApiManager.ReleaseAll();
        }
```

**Comment by higankanshi** [comment]
I'll try it later.

**Comment by bbougot** [comment]
You should await the mediaPlayer.Stop() prior to dispose it in your Window_Closing method.

**Comment by sepehr1014** [comment]
Actually now it seems `Stop` function freezes. It's just stuck in the `while (_stopping)` loop ...

**Comment by higankanshi** [comment]
I fixed it and pull it to master.

Some changes on Stop:
Now we have 3 ways to stop the media.
01."Stop" Method
```CSharp
vlcPlayer.Stop();
//You can't add other code after this.
```

02."BeginStop" Method
```CSharp
vlcPlayer.BeginStop(ar =>
{
	//TODO: after stop
});
//You can't add other code after this.
```

02."StopAsync" Method
It's only used in .Net4.5
```CSharp
await vlcPlayer.StopAsync()
//TODO: after stop
```

**Comment by higankanshi** [comment]
BTW, you don't need ```ApiManager.ReleaseAll();``` now.

**Comment by sepehr1014** [comment]
Really great work. Though there seems to be a problem with `VlcPlayer.BeginStop` callback. When a media is already being played, the code below throws exception "most of the time":
```
OpenFileDialog d = new OpenFileDialog();

            if (d.ShowDialog() == true)
            {
                player.BeginStop((ar) =>
                {
                    player.LoadMedia(d.FileName);
                    player.Play();
                });
            }
```
Exception:
```
System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=xZune.VLC
  StackTrace:
       at xZune.Vlc.VlcMediaPlayer.set_Media(VlcMedia value) in c:\Users\Sepehr\Desktop\xZune.Vlc-master\xZune.Vlc\VlcMediaPlayer.cs:line 468
       at xZune.Vlc.Wpf.VlcPlayer.LoadMedia(String path) in c:\Users\Sepehr\Desktop\xZune.Vlc-master\xZune.Vlc.Wpf\VlcPlayer.cs:line 721
       at WpfApplication1.MainWindow.<>c__DisplayClass2.<btnChange_Click>b__0(IAsyncResult ar) in c:\Users\Sepehr\Desktop\xZune.Vlc-master\WpfApplication1\MainWindow.xaml.cs:line 52
       at xZune.Vlc.Wpf.VlcPlayer.<>c__DisplayClassc.<BeginStop>b__a(IAsyncResult aresult) in c:\Users\Sepehr\Desktop\xZune.Vlc-master\xZune.Vlc.Wpf\VlcPlayer.cs:line 807
       at System.Runtime.Remoting.Messaging.AsyncResult.SyncProcessMessage(IMessage msg)
       at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)
       at System.Runtime.Remoting.Proxies.AgileAsyncWorkerItem.ThreadPoolCallBack(Object o)
       at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
  InnerException: 
```

**Comment by higankanshi** [comment]
I test it, but I catch no exception.
Maybe you can see the sample.

**Comment by higankanshi** [comment]
I test it, but I catch no exception.
Maybe you can see the sample.

**Comment by sepehr1014** [comment]
Please remove `xZune.Vlc.Wpf.ApiManager.ReleaseAll()` from README file too.
