### ISSUE TITLE
Passing string to VlcPlayer.LoadMedia in Stop callback throws exception

### ISSUE THREAD

**Issue by sepehr1014** [higankanshi/xZune.Vlc#23]
This code works fine:
```C#
OpenFileDialog d = new OpenFileDialog();

            if (d.ShowDialog() == true)
            {
                player.BeginStop((ar) =>
                {
                    player.LoadMedia(new Uri(d.FileName));
                    player.Play();
                });
            }
```
But when a file is already playing, using the code below throws exception:
```C#
OpenFileDialog d = new OpenFileDialog();

            if (d.ShowDialog() == true)
            {
                player.BeginStop((ar) =>
                {
                    player.LoadMedia(d.FileName);
                    player.Play();
                });
            }
```
The exception:
```
System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=xZune.VLC
  StackTrace:
       at xZune.Vlc.VlcMediaPlayer.set_Media(VlcMedia value) in c:\Users\Sepehr\Desktop\xZune.Vlc-master\xZune.Vlc\VlcMediaPlayer.cs:line 468
       at xZune.Vlc.Wpf.VlcPlayer.LoadMedia(String path) in c:\Users\Sepehr\Desktop\xZune.Vlc-master\xZune.Vlc.Wpf\VlcPlayer.cs:line 721
       at WpfApplication1.MainWindow.<>c__DisplayClass2.<btnChange_Click>b__0(IAsyncResult ar) in c:\Users\Sepehr\Desktop\xZune.Vlc-master\WpfApplication1\MainWindow.xaml.cs:line 52
       at xZune.Vlc.Wpf.VlcPlayer.<>c__DisplayClassc.<BeginStop>b__a(IAsyncResult aresult) in c:\Users\Sepehr\Desktop\xZune.Vlc-master\xZune.Vlc.Wpf\VlcPlayer.cs:line 807
       at System.Runtime.Remoting.Messaging.AsyncResult.SyncProcessMessage(IMessage msg)
       at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)
       at System.Runtime.Remoting.Proxies.AgileAsyncWorkerItem.ThreadPoolCallBack(Object o)
       at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
  InnerException: 
```

**Comment by higankanshi** [comment]
I try it in sample, I can't reappear this issue.

Can you see the LoadMedia method?
Maybe some wrong in Vlc.CreateMediaFormPath method.
Look about what it return in Vlc.CreateMediaFormPath.

**Comment by sepehr1014** [comment]
In `LoadMedia` after `CreateMediaFormPath`, here's what I get for `VlcMediaPlayer.Media` in the immediate window:
```
VlcMediaPlayer.Media
{xZune.Vlc.VlcMedia}
    _disposed: false
    _onDurationChanged: {Method = {Void OnDurationChanged(xZune.Vlc.Interop.Core.Events.LibVlcEventArgs ByRef, IntPtr)}}
    _onDurationChangedHandle: {System.Runtime.InteropServices.GCHandle}
    _onFreed: {Method = {Void OnFreed(xZune.Vlc.Interop.Core.Events.LibVlcEventArgs ByRef, IntPtr)}}
    _onFreedHandle: {System.Runtime.InteropServices.GCHandle}
    _onMetaChanged: {Method = {Void OnMetaChanged(xZune.Vlc.Interop.Core.Events.LibVlcEventArgs ByRef, IntPtr)}}
    _onMetaChangedHandle: {System.Runtime.InteropServices.GCHandle}
    _onParsedChanged: {Method = {Void OnParsedChanged(xZune.Vlc.Interop.Core.Events.LibVlcEventArgs ByRef, IntPtr)}}
    _onParsedChangedHandle: {System.Runtime.InteropServices.GCHandle}
    _onStateChanged: {Method = {Void OnStateChanged(xZune.Vlc.Interop.Core.Events.LibVlcEventArgs ByRef, IntPtr)}}
    _onStateChangedHandle: {System.Runtime.InteropServices.GCHandle}
    _onSubItemAdded: {Method = {Void OnSubItemAdded(xZune.Vlc.Interop.Core.Events.LibVlcEventArgs ByRef, IntPtr)}}
    _onSubItemAddedHandle: {System.Runtime.InteropServices.GCHandle}
    _stats: {xZune.Vlc.Interop.Media.MediaStats}
    Duration: {-00:00:00.0010000}
    DurationChanged: null
    EventManager: {xZune.Vlc.VlcEventManager}
    Freed: null
    InstancePointer: 176164624
    IsParsed: false
    MetaChanged: null
    Mrl: "file:///C:/Users/Sepehr/Desktop/Sample%20Files/Sample%20Videos/Nature.mp4"
    ParsedChanged: null
    State: NothingSpecial
    StateChanged: null
    Stats: 'VlcMediaPlayer.Media.Stats' threw an exception of type 'System.AccessViolationException'
    SubItemAdded: null
    Subitems: 0
    UserData: 0
```
Is `Stats` supposed to throw exception?
And setting the media throws the above exception. Though the exception is not always thrown. If I set breakpoints and continue step by step, it won't throw exception. I think there something wrong about threads ...

**Comment by higankanshi** [comment]
Ummmm.... Can you give me your code and binary files?

I'll check it later.
Best with the media file.

**Comment by higankanshi** [comment]
Stats only work with network stream.
